// Tag options for post creation.
// values must match the backend pattern: ^[a-z0-9-]+$ (lowercase, numbers, hyphens only)

export const ACADEMIC_TAGS = [
  { value: 'general-study', label: 'General Study' },
  { value: 'exam-grind', label: 'Exam Grind' },
  { value: 'programming', label: 'Programming' },
  { value: 'hackathons', label: 'Hackathons' },
  { value: 'frontend-dev', label: 'Frontend Dev' },
  { value: 'backend-dev', label: 'Backend Dev' },
  { value: 'ai-ml', label: 'AI/ML' },
  { value: 'data-analysis', label: 'Data Analysis' },
  { value: 'job-grind', label: 'Job Grind' },
  { value: 'projects-grind', label: 'Projects Grind' },
  { value: 'conferences', label: 'Conferences' },
  { value: 'thesis-work', label: 'Thesis Work' },
  { value: 'research-work', label: 'Research Work' },
  { value: 'hlpl1', label: 'HLPL1' },
  { value: 'hlpl2', label: 'HLPL2' },
  { value: 'swe-subject', label: 'SWE Subject' },
  { value: 'language-study', label: 'Language Study' },
  { value: 'engineering', label: 'Engineering' },
  { value: 'online-studying', label: 'Online Studying' },
  { value: 'notes-making', label: 'Notes Making' },
];

export const ACTIVITY_TAGS = [
  { value: 'sports', label: 'Sports' },
  { value: 'football', label: 'Football' },
  { value: 'basketball', label: 'Basketball' },
  { value: 'gaming', label: 'Gaming' },
  { value: 'fortnite', label: 'Fortnite' },
  { value: 'among-us', label: 'Among Us' },
  { value: 'lethal-company', label: 'Lethal Company' },
  { value: 'skribbl-io', label: 'Skribbl.io' },
  { value: 'competitive-gaming', label: 'Competitive Gaming' },
  { value: 'ranked-grind', label: 'Ranked Grind' },
  { value: 'hangouts', label: 'Hangouts' },
  { value: 'student-life', label: 'Student Life' },
  { value: 'cricket', label: 'Cricket' },
  { value: 'working-out', label: 'Working Out' },
  { value: 'music', label: 'Music' },
  { value: 'instruments', label: 'Instruments' },
  { value: 'board-games', label: 'Board Games' },
  { value: 'chess', label: 'Chess' },
  { value: 'travel', label: 'Travel' },
  { value: 'cooking', label: 'Cooking' },
];
