import { League } from '@/types/league';

export const dummyLeagues: League[] = [
  // ACADEMIC leagues
  {
    id: 1,
    name: 'Physics Society',
    mascot: 'applegrad',
    type: 'ACADEMIC',
    description: 'Weekly problem sessions, guest lectures, and lab meetups for physics students.',
    memberCount: 124,
    createdAt: '2024-01-15T09:00:00Z',
  },
  {
    id: 2,
    name: 'Math League',
    mascot: 'coconutgrad',
    type: 'ACADEMIC',
    description: 'Study groups, contest prep, and collaborative note sharing for all math majors.',
    memberCount: 98,
    createdAt: '2023-11-02T14:30:00Z',
  },
  {
    id: 3,
    name: 'Chemistry Club',
    mascot: 'lemongrad',
    type: 'ACADEMIC',
    description: 'Hands-on demos, journal clubs, and peer tutoring for chemistry coursework.',
    memberCount: 76,
    createdAt: '2023-10-10T12:00:00Z',
  },
  {
    id: 4,
    name: 'Data Science Collective',
    mascot: 'mangograd',
    type: 'ACADEMIC',
    description: 'Workshops on ML, weekly project nights, and hackathon teams.',
    memberCount: 142,
    createdAt: '2024-02-01T18:45:00Z',
  },
  {
    id: 5,
    name: 'Philosophy Circle',
    mascot: 'orangegrad',
    type: 'ACADEMIC',
    description: 'Reading groups and debates covering ethics, logic, and continental thought.',
    memberCount: 34,
    createdAt: '2022-09-20T10:15:00Z',
  },
  {
    id: 6,
    name: 'Engineering Honors',
    mascot: 'peargrad',
    type: 'ACADEMIC',
    description: 'Project showcases, industry talks, and mentorship for high-achieving engineers.',
    memberCount: 58,
    createdAt: '2023-08-05T16:00:00Z',
  },
  {
    id: 7,
    name: 'Literature Society',
    mascot: 'strawbeegrad',
    type: 'ACADEMIC',
    description: 'Poetry nights, author talks, and collaborative workshops on writing.',
    memberCount: 47,
    createdAt: '2021-04-12T08:00:00Z',
  },

  // HOMIES (activities) leagues
  {
    id: 8,
    name: 'Campus Soccer Club',
    mascot: 'apple',
    type: 'HOMIES',
    description: 'Casual and competitive pick-up matches every weekend — all skill levels welcome.',
    memberCount: 63,
    createdAt: '2023-03-18T07:30:00Z',
  },
  {
    id: 9,
    name: 'Weekend Hikers',
    mascot: 'coconut',
    type: 'HOMIES',
    description: 'Organised hikes and overnight trips to nearby trails and national parks.',
    memberCount: 41,
    createdAt: '2022-06-10T06:00:00Z',
  },
  {
    id: 10,
    name: 'Photo Walkers',
    mascot: 'lemon',
    type: 'HOMIES',
    description: 'Monthly themed photo walks and critique sessions for hobbyist photographers.',
    memberCount: 29,
    createdAt: '2024-02-11T13:00:00Z',
  },
  {
    id: 11,
    name: 'Gaming Guild',
    mascot: 'mango',
    type: 'HOMIES',
    description: 'Weekly LAN nights, esports teams, and casual board game meetups.',
    memberCount: 110,
    createdAt: '2023-12-01T20:00:00Z',
  },
  {
    id: 12,
    name: 'Campus Ensemble',
    mascot: 'orange',
    type: 'HOMIES',
    description: 'Instrumental and vocal groups rehearsing for campus concerts and events.',
    memberCount: 52,
    createdAt: '2020-11-25T19:00:00Z',
  },
  {
    id: 13,
    name: 'Dance Crew',
    mascot: 'pear',
    type: 'HOMIES',
    description: 'Choreography workshops, performances, and open practices for dancers.',
    memberCount: 38,
    createdAt: '2021-09-03T17:30:00Z',
  },
  {
    id: 14,
    name: 'Film Society',
    mascot: 'watermelon',
    type: 'HOMIES',
    description: 'Screenings, filmmaker Q&As, and short film nights with student submissions.',
    memberCount: 45,
    createdAt: '2022-01-14T21:00:00Z',
  },
];
